# Town Shields & Armor
# Instructions: Set up each town shield and armor option in this file. Each option has a name, charge and cost-per-resident.
# You may add more options, or remove the default ones. The format is below. Replace text in <> with your own values.
#
# shields:
#   <name>:
#     charge: <shield duration in seconds>
#     cost: <favor cost per town resident>
# armors:
#   <name>:
#     charge: <armor amount in blocks>
#     cost: <favor cost per town resident>
# 
# You can change existing names (Short, Light, etc), charges and costs, and add more options under shields and armors.
# Names can have spaces.
# Lines that begin with "#" (like this one) are comments, and do not change any settings.
# Use a YAML parser to make sure this file is correctly formatted with no errors, like https://yaml-online-parser.appspot.com/
# 
shields:
  Short:
    charge: 1800
    cost: 100
  Intermediate:
    charge: 7200
    cost: 200
  Long:
    charge: 28800
    cost: 300
armors:
  Light:
    charge: 50
    cost: 100
  Medium:
    charge: 200
    cost: 200
  Heavy:
    charge: 800
    cost: 300
