name: Konquest
description: A plugin for land claiming and territory control
author: Rumsfield
version: @version@
api-version: 1.16
load: POSTWORLD
main: com.github.rumsfield.konquest.KonquestPlugin
libraries:
  - org.apache.commons:commons-lang3:3.14.0
depend: [Vault]
softdepend:
  - ProtocolLib
  - ChestShop
  - QuickShop
  - LuckPerms
  - PlaceholderAPI
  - dynmap
  - BlueMap
  - EconomyPlus
  - Economy
  - XConomy
  - Essentials
  - Multiverse-Core
  - Multiverse-Inventories
  - Multiverse-Portals
  - Multiverse-NetherPortals
  - DiscordSRV
  - WorldEdit
  - WorldGuard
loadbefore:
  - SmoothTimber
commands:
  konquest:
    description: Base command, displays help menu
    aliases: k
    permission: konquest.command
    permission-message: You do not have the base command permission "konquest.command".
    usage: "/<command> [sub-command] [arguments]"

permissions:
  konquest.*:
    description: Gives access to all Konquest permissions
    default: op
    children:
      konquest.command: true
      konquest.command.*: true
      konquest.create.*: true
      konquest.admin.*: true
      konquest.directive.*: true
      konquest.compass: true
      konquest.join: true
      konquest.chatcolor: true

  konquest.command:
    description: Base command permission
    default: true
    
  konquest.command.*:
    description: Gives access to all Konquest commands
    default: op
    children:
      konquest.command.help: true
      konquest.command.info: true
      konquest.command.chat: true
      konquest.command.claim: true
      konquest.command.unclaim: true
      konquest.command.list: true
      konquest.command.map: true
      konquest.command.settle: true
      konquest.command.travel: true
      konquest.command.favor: true
      konquest.command.quest: true
      konquest.command.score: true
      konquest.command.spy: true
      konquest.command.stats: true
      konquest.command.prefix: true
      konquest.command.kingdom: true
      konquest.command.town: true
      konquest.command.fly: true
      konquest.command.border: true

  konquest.command.help:
    description: Display help in chat
    default: true
    
  konquest.command.info:
    description: Display info on a kingdom, town or player
    default: true
    
  konquest.command.chat:
    description: Toggle between global and kingdom-only chat
    default: true

  konquest.command.claim:
    description: Claim land for an adjacent town
    default: true
    
  konquest.command.unclaim:
    description: Unclaim land for a town
    default: true
    
  konquest.command.list:
    description: Display a list of kingdoms or towns
    default: true

  konquest.command.map:
    description: Display a map of surrounding land in chat
    default: true

  konquest.command.settle:
    description: Settle a new town
    default: true

  konquest.command.travel:
    description: Travel to a friendly town
    default: true

  konquest.command.favor:
    description: Display your favor and costs
    default: true
    
  konquest.command.quest:
    description: Display the quest book
    default: true

  konquest.command.score:
    description: Display a kingdom's score
    default: true
    
  konquest.command.spy:
    description: Purchase a map centered on an enemy town
    default: true
    
  konquest.command.stats:
    description: Display the stats book
    default: true
    
  konquest.command.prefix:
    description: Choose a prefix for your name in chat
    default: true

  konquest.command.kingdom:
    description: Manage a kingdom
    default: true

  konquest.command.town:
    description: Manage a town
    default: true

  konquest.command.fly:
    description: Fly in friendly territory
    default: op
    
  konquest.command.border:
    description: Toggle particle borders of territories and plots
    default: true
    
  konquest.create.*:
    description: Gives access to creating all territories
    default: op
    children:
      konquest.create.camp: true
      konquest.create.town: true
      konquest.create.kingdom: true

  konquest.create.camp:
    description: Create barbarian camps
    default: true

  konquest.create.town:
    description: Create towns as a kingdom member
    default: true

  konquest.create.kingdom:
    description: Create new kingdoms
    default: true

  konquest.admin.*:
    description: All admin commands
    default: op
    children:
      konquest.admin.bypass: true
      konquest.admin.camp: true
      konquest.admin.capture: true
      konquest.admin.claim: true
      konquest.admin.flag: true
      konquest.admin.help: true
      konquest.admin.kingdom: true
      konquest.admin.monument: true
      konquest.admin.reload: true
      konquest.admin.ruin: true
      konquest.admin.sanctuary: true
      konquest.admin.save: true
      konquest.admin.settravel: true
      konquest.admin.stat: true
      konquest.admin.town: true
      konquest.admin.travel: true
      konquest.admin.unclaim: true
  
  konquest.admin.bypass:
    description: Toggle admin bypass mode to ignore Konquest protections
    default: op
  
  konquest.admin.camp:
    description: Manage player Barbarian Camp territories
    default: op
    
  konquest.admin.capture:
    description: Force a town to be captured by another Kingdom
    default: op
    
  konquest.admin.claim:
    description: Claim land chunks for the nearest territory
    default: op
  
  konquest.admin.flag:
    description: Set property flags for Kingdoms and territories
    default: op
  
  konquest.admin.help:
    description: Display the admin help message
    default: op
  
  konquest.admin.kingdom:
    description: Manage player and admin Kingdoms
    default: op
  
  konquest.admin.monument:
    description: Manage Monument Templates
    default: op
  
  konquest.admin.reload:
    description: Reload plugin configuration files
    default: op
  
  konquest.admin.ruin:
    description: Manage Ruin territories
    default: op

  konquest.admin.sanctuary:
    description: Manage Sanctuary territories
    default: op

  konquest.admin.save:
    description: Save all plugin data to files
    default: op
  
  konquest.admin.settravel:
    description: Set the travel spawn point for the nearest territory
    default: op
  
  konquest.admin.stat:
    description: Manage player stats
    default: op
  
  konquest.admin.town:
    description: Manage Town and Kingdom Capital territories
    default: op
    
  konquest.admin.travel:
    description: Teleport to any kingdom or territory
    default: op
  
  konquest.admin.unclaim:
    description: Return a claimed chunk of land to the Wild
    default: op

  konquest.directive.*:
    description: Gives access to all Konquest directives
    default: true
    children:
      konquest.directive.kingdom: true
      konquest.directive.settle: true
      konquest.directive.claim: true
      konquest.directive.build: true
      konquest.directive.golem: true
      konquest.directive.armor: true
      konquest.directive.enchant: true
      konquest.directive.attack: true
      konquest.directive.capture: true
      konquest.directive.kill: true

  konquest.directive.kingdom:
    description: Receive a reward for creating your first kingdom
    default: true

  konquest.directive.settle:
    description: Receive a reward for settling your first town
    default: true
    
  konquest.directive.claim:
    description: Receive a reward for claiming your first 5 chunks
    default: true
    
  konquest.directive.build:
    description: Receive a reward for building structures in a town
    default: true
    
  konquest.directive.golem:
    description: Receive a reward for creating an iron golem in a town
    default: true
    
  konquest.directive.armor:
    description: Receive a reward for crafting a set of iron armor
    default: true
    
  konquest.directive.enchant:
    description: Receive a reward for enchanting tools and weapons
    default: true
    
  konquest.directive.attack:
    description: Receive a reward for attacking an enemy town
    default: true
    
  konquest.directive.capture:
    description: Receive a reward for capturing an enemy town
    default: true
    
  konquest.directive.kill:
    description: Receive a reward for killing an enemy player
    default: true
    
  konquest.compass:
    description: Compass points to nearest enemy town
    default: true
  
  konquest.join:
    description: Join a kingdom
    default: op
    
  konquest.discount:
    description: Applies a percent discount on all Favor withdraws
    default: false
    
  konquest.prefix:
    description: Grants access to a custom prefix
    default: false

  konquest.chatcolor:
    description: Allows players to use color format codes in chat messages
    default: false
